2022-08-15 10:16:59,004 INFO: Microblog startup [in C:\Git-CMU\module8-resilience\CMU-SOEN-Microblog-Assignment-Tejash\app\__init__.py:89]
2022-08-15 10:17:08,574 INFO: Microblog startup [in C:\Git-CMU\module8-resilience\CMU-SOEN-Microblog-Assignment-Tejash\app\__init__.py:89]
2022-08-15 10:18:02,027 INFO: Microblog startup [in C:\Git-CMU\module8-resilience\CMU-SOEN-Microblog-Assignment-Tejash\app\__init__.py:89]
2022-08-15 10:19:24,651 ERROR: Exception on /export_posts [GET] [in C:\Users\tpatel\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\flask\app.py:1455]
Traceback (most recent call last):
  File "C:\Users\tpatel\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\redis\connection.py", line 559, in connect
    sock = self._connect()
  File "C:\Users\tpatel\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\redis\connection.py", line 615, in _connect
    raise err
  File "C:\Users\tpatel\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\redis\connection.py", line 603, in _connect
    sock.connect(socket_address)
ConnectionRefusedError: [WinError 10061] No connection could be made because the target machine actively refused it

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\tpatel\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\flask\app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\tpatel\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\flask\app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\tpatel\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\flask\app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\tpatel\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\flask\app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "C:\Users\tpatel\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\flask_login\utils.py", line 303, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "C:\Git-CMU\module8-resilience\CMU-SOEN-Microblog-Assignment-Tejash\app\main\routes.py", line 213, in export_posts
    current_user.launch_task('export_posts', _('Exporting posts...'))
  File "C:\Git-CMU\module8-resilience\CMU-SOEN-Microblog-Assignment-Tejash\app\models.py", line 177, in launch_task
    rq_job = current_app.task_queue.enqueue('app.tasks.' + name, self.id,
  File "C:\Users\tpatel\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\rq\queue.py", line 508, in enqueue
    return self.enqueue_call(
  File "C:\Users\tpatel\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\rq\queue.py", line 406, in enqueue_call
    return self.enqueue_job(job, pipeline=pipeline, at_front=at_front)
  File "C:\Users\tpatel\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\rq\queue.py", line 566, in enqueue_job
    job.save(pipeline=pipe)
  File "C:\Users\tpatel\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\rq\job.py", line 663, in save
    if self.get_redis_server_version() >= (4, 0, 0):
  File "C:\Users\tpatel\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\rq\job.py", line 671, in get_redis_server_version
    self.redis_server_version = get_version(self.connection)
  File "C:\Users\tpatel\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\rq\utils.py", line 282, in get_version
    return tuple(int(i) for i in connection.info("server")["redis_version"].split('.')[:3])
  File "C:\Users\tpatel\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\redis\client.py", line 1306, in info
    return self.execute_command('INFO', section)
  File "C:\Users\tpatel\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\redis\client.py", line 898, in execute_command
    conn = self.connection or pool.get_connection(command_name, **options)
  File "C:\Users\tpatel\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\redis\connection.py", line 1192, in get_connection
    connection.connect()
  File "C:\Users\tpatel\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\redis\connection.py", line 563, in connect
    raise ConnectionError(self._error_message(e))
redis.exceptions.ConnectionError: Error 10061 connecting to None:6379. No connection could be made because the target machine actively refused it.
2022-08-18 15:53:29,599 INFO: Microblog startup [in C:\Git-CMU\module8-resilience\CMU-SOEN-Microblog-Assignment-Tejash\app\__init__.py:89]
