2022-06-24 16:33:03,449 INFO: Microblog startup [in C:\Git-CMU\Module3-new-feature\CMU-SOEN-Microblog-Assignment-Tejash\app\__init__.py:89]
2022-06-24 16:33:08,612 INFO: Microblog startup [in C:\Git-CMU\Module3-new-feature\CMU-SOEN-Microblog-Assignment-Tejash\app\__init__.py:89]
2022-06-24 16:33:34,834 INFO: Microblog startup [in C:\Git-CMU\Module3-new-feature\CMU-SOEN-Microblog-Assignment-Tejash\app\__init__.py:89]
2022-06-24 16:50:45,915 INFO: Microblog startup [in C:\Git-CMU\Module3-new-feature\CMU-SOEN-Microblog-Assignment-Tejash\app\__init__.py:89]
2022-06-26 21:11:23,379 INFO: Microblog startup [in C:\Git-CMU\Module3-new-feature\CMU-SOEN-Microblog-Assignment-Tejash\app\__init__.py:89]
2022-06-26 21:20:37,762 INFO: Microblog startup [in C:\Git-CMU\Module3-new-feature\CMU-SOEN-Microblog-Assignment-Tejash\app\__init__.py:89]
2022-06-26 21:20:44,371 ERROR: Exception on /edit_profile [GET] [in C:\Users\tpatel\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\flask\app.py:1455]
Traceback (most recent call last):
  File "C:\Users\tpatel\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\flask\app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\tpatel\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\flask\app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\tpatel\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\flask\app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\tpatel\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\flask\app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "C:\Users\tpatel\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\flask_login\utils.py", line 303, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "C:\Git-CMU\Module3-new-feature\CMU-SOEN-Microblog-Assignment-Tejash\app\main\routes.py", line 104, in edit_profile
    form.email.data = current_app.email
AttributeError: 'Flask' object has no attribute 'email'
2022-06-26 21:20:51,914 ERROR: Exception on /edit_profile [GET] [in C:\Users\tpatel\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\flask\app.py:1455]
Traceback (most recent call last):
  File "C:\Users\tpatel\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\flask\app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\tpatel\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\flask\app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\tpatel\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\flask\app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\tpatel\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\flask\app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "C:\Users\tpatel\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\flask_login\utils.py", line 303, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "C:\Git-CMU\Module3-new-feature\CMU-SOEN-Microblog-Assignment-Tejash\app\main\routes.py", line 104, in edit_profile
    form.email.data = current_app.email
AttributeError: 'Flask' object has no attribute 'email'
2022-06-26 21:22:20,909 INFO: Microblog startup [in C:\Git-CMU\Module3-new-feature\CMU-SOEN-Microblog-Assignment-Tejash\app\__init__.py:89]
2022-06-26 21:33:49,522 INFO: Microblog startup [in C:\Git-CMU\Module3-new-feature\CMU-SOEN-Microblog-Assignment-Tejash\app\__init__.py:89]
2022-06-26 21:33:57,840 INFO: Microblog startup [in C:\Git-CMU\Module3-new-feature\CMU-SOEN-Microblog-Assignment-Tejash\app\__init__.py:89]
2022-06-26 21:34:11,327 ERROR: Exception on /auth/login [POST] [in C:\Users\tpatel\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\flask\app.py:1455]
Traceback (most recent call last):
  File "C:\Users\tpatel\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\flask\app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\tpatel\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\flask\app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\tpatel\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\flask\app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\tpatel\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\flask\app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "C:\Git-CMU\Module3-new-feature\CMU-SOEN-Microblog-Assignment-Tejash\app\auth\routes.py", line 26, in login
    user = User.query.filter_by(email=form.email.data).first()
AttributeError: 'LoginForm' object has no attribute 'email'
2022-06-26 21:34:29,434 ERROR: Exception on /auth/login [POST] [in C:\Users\tpatel\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\flask\app.py:1455]
Traceback (most recent call last):
  File "C:\Users\tpatel\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\flask\app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\tpatel\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\flask\app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\tpatel\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\flask\app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\tpatel\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\flask\app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "C:\Git-CMU\Module3-new-feature\CMU-SOEN-Microblog-Assignment-Tejash\app\auth\routes.py", line 26, in login
    user = User.query.filter_by(email=form.email.data).first()
AttributeError: 'LoginForm' object has no attribute 'email'
2022-06-26 21:34:47,693 ERROR: Exception on /auth/login [POST] [in C:\Users\tpatel\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\flask\app.py:1455]
Traceback (most recent call last):
  File "C:\Users\tpatel\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\flask\app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\tpatel\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\flask\app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\tpatel\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\flask\app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\tpatel\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\flask\app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "C:\Git-CMU\Module3-new-feature\CMU-SOEN-Microblog-Assignment-Tejash\app\auth\routes.py", line 26, in login
    user = User.query.filter_by(email=form.email.data).first()
AttributeError: 'LoginForm' object has no attribute 'email'
2022-06-26 21:36:27,259 INFO: Microblog startup [in C:\Git-CMU\Module3-new-feature\CMU-SOEN-Microblog-Assignment-Tejash\app\__init__.py:89]
